import type { CategoryCatalogRecord } from '../../../studio-types/src/archive';

export const CATEGORY_CATALOG_CREATED_AT = '2026-04-21T00:00:00.000Z';

export const DEFAULT_CATEGORY_CATALOG: CategoryCatalogRecord[] = [
  {
    id: 'cat_software_development',
    name: 'Software Development',
    description: 'Programming, debugging, architecture, developer tools, infrastructure, and code workflows.',
    color: '#2563eb',
    sortOrder: 10,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['software', 'development', 'programming', 'coding', 'code'],
  },
  {
    id: 'cat_product_ux_design',
    name: 'Product & UX Design',
    description: 'Product thinking, user experience, interface design, prototyping, and usability decisions.',
    color: '#7c3aed',
    sortOrder: 20,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['product', 'ux', 'ui', 'design', 'product design'],
  },
  {
    id: 'cat_writing_communication',
    name: 'Writing & Communication',
    description: 'Drafting, editing, messaging, documentation, summaries, and communication planning.',
    color: '#db2777',
    sortOrder: 30,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['writing', 'communication', 'email', 'copywriting', 'docs'],
  },
  {
    id: 'cat_research_analysis',
    name: 'Research & Analysis',
    description: 'Research, synthesis, investigation, comparison, data analysis, and evidence review.',
    color: '#4f46e5',
    sortOrder: 40,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['research', 'analysis', 'analytics', 'investigation'],
  },
  {
    id: 'cat_learning_study',
    name: 'Learning & Study',
    description: 'Teaching, tutoring, study support, explanations, practice, and educational planning.',
    color: '#0891b2',
    sortOrder: 50,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['learning', 'study', 'education', 'course'],
  },
  {
    id: 'cat_engineering_science',
    name: 'Engineering & Science',
    description: 'Technical engineering, science, mathematics, experiments, systems, and applied problem solving.',
    color: '#0d9488',
    sortOrder: 60,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['engineering', 'science', 'math', 'physics'],
  },
  {
    id: 'cat_legal_administrative',
    name: 'Legal & Administrative',
    description: 'Legal, policy, compliance, forms, administrative processes, and procedural records.',
    color: '#475569',
    sortOrder: 70,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['legal', 'administrative', 'admin', 'compliance'],
  },
  {
    id: 'cat_business_operations',
    name: 'Business & Operations',
    description: 'Business planning, operations, sales, finance, strategy, workflows, and organizational work.',
    color: '#059669',
    sortOrder: 80,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['business', 'operations', 'ops', 'strategy'],
  },
  {
    id: 'cat_personal_planning',
    name: 'Personal Planning',
    description: 'Personal organization, scheduling, decisions, travel planning, goals, and life administration.',
    color: '#ca8a04',
    sortOrder: 90,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['personal', 'planning', 'life admin', 'schedule'],
  },
  {
    id: 'cat_health_fitness',
    name: 'Health & Fitness',
    description: 'Health, fitness, wellness, nutrition, habits, and non-diagnostic personal care topics.',
    color: '#16a34a',
    sortOrder: 100,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['health', 'fitness', 'wellness', 'nutrition'],
  },
  {
    id: 'cat_shopping_products',
    name: 'Shopping & Products',
    description: 'Shopping, product research, comparisons, buying decisions, reviews, and recommendations.',
    color: '#ea580c',
    sortOrder: 110,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['shopping', 'products', 'buying', 'reviews'],
  },
  {
    id: 'cat_general_misc',
    name: 'General / Misc',
    description: 'Broad, mixed, casual, or uncategorized conversations that do not fit another stable category.',
    color: '#64748b',
    sortOrder: 120,
    createdAt: CATEGORY_CATALOG_CREATED_AT,
    updatedAt: CATEGORY_CATALOG_CREATED_AT,
    status: 'active',
    replacementCategoryId: null,
    aliases: ['general', 'misc', 'miscellaneous', 'other'],
  },
];
